### ISSUE TITLE
MSCC Locks up during QRO PWR Calibration

### ISSUE THREAD

**Issue by N8VET** [w4mmp/Solidus#15]
When on Solidus Tab and selecting a band to calibrate QRO power, MSCC locks up. Most bands work OK except when selecting 60M, 12M and 10M MSCC locks up. The only option is to reboot RPi Stew

**Comment by N8VET** [comment]
Playing with it more I see it locks up on any band.  Sometimes the first time others after calibrating a couple of bands.

**Comment by w4mmp** [comment]
Hi Stew,
Once I have my amplifier installed installed in my Solidus,  I will correct the issue.

**Comment by w4mmp** [comment]
I believe the issue has been fixed.
